### ISSUE TITLE
missmatch to dockerhub

### ISSUE THREAD

**Issue by tbleiker** [mumble-voip/mumble-docker#1]
Most probably you are already working on it and I am just too early/impatient... :smile: But the image on dockerhub does not seem to correspond to the current state of this repo. On the dockerhub image the entrypoint file is called docker-entrypoint.sh and is different to the entrypoint.sh in this rep.

**Comment by Krzmbrzl** [comment]
Yeah we did not get to update the image yet. I'll work on it right now though ^^

**Comment by Krzmbrzl** [comment]
There you go - image updated :D
