### ISSUE TITLE
CONFIG_FILE is readonly, preventing the use of a custom config file

### ISSUE THREAD

**Issue by tperrindell** [mumble-voip/mumble-docker#10]
Hi,

I imported my existing config when I migrated from a standalone server installation to docker.

Yesterday's update broke my installation. At first I thought it was due to the UID, so I had to change my system for it to match the values of 1000/1000, but that didn't fix anything.

When reading the new commit for the entrypoint.sh, 6a9d8f5cdb9e091db8c55c4e5d405d1f2d15f4bb

The variable CONFIG_FILE is set as readonly.

Therefore, the code at lines 58ish can't work : 
```
if [[ -f "$MUMBLE_CUSTOM_CONFIG_FILE" ]]; then
	echo "Using manually specified config file at $MUMBLE_CUSTOM_CONFIG_FILE"
	echo "All MUMBLE_CONFIG variables will be ignored"
	CONFIG_FILE="$MUMBLE_CUSTOM_CONFIG_FILE"
else
```
Because the variable is readonly...

Can you revert that commit or correct the problem please ?

**Comment by azlux** [comment]
Should be fixed now.
