### ISSUE TITLE
Error while starting container with unset DEBUG variable

### ISSUE THREAD

**Issue by akhilman** [mumble-voip/mumble-docker#11]
I have an error while starting this container
```
//./docker-entrypoint.sh: line 104: [: : integer expression expected
```
I believe line right here:
https://github.com/mumble-voip/mumble-docker/blob/0dceaf54f5106602dfcdedb12e3a9869a624da02/docker-entrypoint.sh#L104

should be replaced by:
```bash
if [ -z "$DEBUG" ] || [ "$DEBUG" == 1 ]; then
```
or
```bash
if [ ! -z "$DEBUG" ] && [ "$DEBUG" == 1 ]; then
```

**Comment by azlux** [comment]
Did you have the last version ?
This issue should be fix with https://github.com/mumble-voip/mumble-docker/commit/6985fd658566b11a8e3c4d62ed06a76a79deeac7

Can you execute inside your container : `cat /docker-entrypoint.sh | grep -iF debug` to check if you have the good file ?

**Comment by akhilman** [comment]
Yes I have last version.

` [ ! -z "$DEBUG" ]` means `not is empty string $DEBUG`

therefore
`[ ! -z "$DEBUG" ] || [ "$DEBUG" == 1 ]` means `not is empty string $DEBUG or $DEBUG as number equals 1`

If we have $DEBUG empty, then
`not is empty string "" or "" as number equals 1` -> 
`not true or "" as number equals 1` -> 
`false or "" as number equals 1` -> 
`"" as number equals 1` -> 
error.

**Comment by azlux** [comment]
Indeed, I should replace this line by : 
```bash
if [ ! -z "$DEBUG" ] && [ "$DEBUG" == true ]; then
```
