### ISSUE TITLE
Modified license, no official attribution?

### ISSUE THREAD

**Issue by sudoforge** [mumble-voip/mumble-docker#13]
Really? This project is a **copy** of mine: https://github.com/sudoforge/docker-mumble-server, yet it completely lacks any sort of attribution to me. You've even modified the license. That is not how open source works, and as-is, this is a violation of my intellectual property rights,

**Comment by sudoforge** [comment]
The only "attribution" here is a failure to remove references to me in all of the files:

```
➜ git clone gh:mumble-voip/mumble-docker.git && cd mumble-docker

➜ rg 'sudoforge'
config/murmur.ini
102:welcometext="<br />Welcome to this server running <b>sudoforge/mumble-server</b>. <br />Enjoy your stay!<br />"
```

**Comment by Krzmbrzl** [comment]
Okay after having had a quick chat with azlux about this on our Matrix channel, it has been verified that the original source for this Docker repo has been a fork of your repo @sudoforge.

This docker repo has been created somewhat in a hurry, because we had some issues with the static Linux server and thus there was a void that needed to be filled quickly. In that hectic, proper attribution has been forgotten.
I will immediately fix this situation by adding the necessary attributions.

We apologize for not having thought about this earlier and hope you are okay with the changes that will be made to remedy the situation.

**Comment by Krzmbrzl** [comment]
Done. Let me know, if there is still something missing.

**Comment by sudoforge** [comment]
Sorry for the lack of replies, it's currently my work day and, well, meetings abound.

I'm glad that we were able to properly identify that this is a derivative work, and appreciate the addition of attribution to the repository; the only problem I had with this existing was that we lacked attribution.

I'll be archiving my repository and deprecating my image in favor of this tree.

**Comment by sudoforge** [comment]
Would we be open to rebasing the development that has been done here on top of my tree, so that users and contributors have the full development history to pick from?

I'm happy to do this in a sane way that allows any ongoing work to be rebased fairly simply, but it would require a force push to the head branch.

**Comment by Krzmbrzl** [comment]
I suppose that at this stage it would be fine to have a force push at this point. But the development is mainly driven by @azlux here, so I'll leave the decision up to him.

**Comment by sudoforge** [comment]
I asked it in an amiguous way, but from the standpoint of being legally correct, the previous commits in this repository do not currently contain attribution, and as such, the repository still infringes on my intellectual property rights. Additionally, while I'm... fine with it, labeling the license as the "original license" is not _really_ appropriate; the MIT license stipulates that the copyright notice must be included in "all copies or substantial portions of the Software", meaning that it is the _current_ license for non-derivitive work.

**Comment by sudoforge** [comment]
@azlux thoughts?

**Comment by sudoforge** [comment]
> The source code is licensed under MIT, except that which is originally written by Mumble (the organization). In effect, it is dual-licensed.

To make this clear, files with my intellectual property could contain a license comment and/or SPDX header.

To make this simple for the Mumble team and because I wish to resolve this amicably, I will submit a PR to this repository with these changes that can be used to force push to the master branch.

**Comment by azlux** [comment]
Hi,
I saw this issue, but without real internet access, thank to @Krzmbrzl for the suitable answers during my silence.

I didn't want to hide the original creator of the project, and in the new mumble version hurry, I forgot many things on the code, especially the note and license about the initial intellectual property of the project.

What I had in mind was making a double license (in the same file) to have the initial license and the new license 
in the same location to respect the initial author (@sudoforge) and the work of mumble team.
In this license we will add the last commit from the initial repo before the fork : https://github.com/sudoforge/docker-mumble-server/tree/b3eaacbab12e4ac4ddd01a6f7b3dc6a555fd2a07. This way, we have the exact point of the previous work and the initial contributors.

Making a PR to get all previous commit make no sense for me, it's really a GitHub point of view.

Best regards,
Az

**Comment by sudoforge** [comment]
It honestly doesn't matter that it makes "no sense" to either of you. As I've explained before, each commit in a Git repository is a snapshot, not a patch, and is therefore an archive of the code. Because the earlier commits contain no attribution, they are in violation of the license on the source code.
