### ISSUE TITLE
Accept options not existing in `/etc/mumble/bare_config.ini` and log warning instead of exiting with error

### ISSUE THREAD

**Issue by pawlakm** [mumble-voip/mumble-docker#13]
Currently the default behavior of [entrypoint.sh](https://github.com/mumble-voip/mumble-docker/blob/6535e9dfc049c0e033ca50b391e3825f7dd0885d/entrypoint.sh#L72) is to exit with error when an `MUMBLE_CONFIGURATION_` option is set in the `docker-compose.yml` file but is not existing in `/etc/mumble/bare_config.ini` which is copied from upstream [/scripts/murmur.ini](https://github.com/mumble-voip/mumble/blob/master/scripts/murmur.ini).

While I understand the rationale behind this approach, the problem with this behavior is that if a valid option is missing from `/etc/mumble/bare_config.ini` then it cannot be set in `docker_compose.yml`. From an end user perspective, this is quite annoying. I have currently two examples of missing configurations: [`listenersperchannel`](https://wiki.mumble.info/wiki/Murmur.ini#listenersperchannel) and [`listenersperuser`](https://wiki.mumble.info/wiki/Murmur.ini#listenersperuser).

IMHO a better approach would be to set provided options even if they are missing in `/etc/mumble/bare_config.ini` and instead of an error log a warning stating that as the configuration option is missing in the bare-config, it's not sure that it will be correctly applied and as such it's user's responibility to verify it. 

This would allow to make `mumble-docker` more robust to this type of issues in upstream project.

Note: if I'm not wrong, if the user provides his own mumble configuration file instead of going the `MUMBLE_CONFIGURATION_` way, not existing options in `/etc/mumble/bare_config.ini` are accepted anyway.

**Comment by Krzmbrzl** [comment]
Fixed via #14
