### ISSUE TITLE
Error while loading shared libraries: libQt5Core.so.5

### ISSUE THREAD

**Issue by DcR-NL** [mumble-voip/mumble-docker#14]
Latest only outputs:
```
Command used to start the mumble-server : /usr/bin/mumble-server -fg -ini /etc/murmur/murmur.ini -v
/usr/bin/mumble-server: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

Run command:
`sudo docker run -d -p 64738:64738/tcp -p 64738:64738/udp --name mumble-server-001 -e DEBUG=0 mumblevoip/mumble-server`

What am I missing here?

**Comment by Krzmbrzl** [comment]
It seems like Qt is not available inside the image :eyes: 
Maybe it got optimized away in the attempts to make the final image as slim as possible...

**Comment by azlux** [comment]
Hi,
It's weird, I don't have any issues with the image.
What's your docker version ? Base OS ? and if the docker is installed in no-privileged mode ?

**Comment by azlux** [comment]
Do you mount a specific config file ?
The lib should be here : /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
Can you try : `docker run -it mumblevoip/mumble-server ls /usr/lib/x86_64-linux-gnu/libQt5Core.so.5`

**Comment by DcR-NL** [comment]
Not that I'm aware of....

```
$ sudo docker run -it mumblevoip/mumble-server bash -c "ls -alih /usr/lib/x86_64-linux-gnu/libQt5Core*"
./docker-entrypoint.sh: line 104: [: : integer expression expected
106 lrwxrwxrwx 1 root root   20 Jan  5 18:57 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 -> libQt5Core.so.5.15.2
263 lrwxrwxrwx 1 root root   20 Jan  5 18:57 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15 -> libQt5Core.so.5.15.2
131 -rw-r--r-- 1 root root 5.4M Jan  5 18:57 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.2
````

Just in case:
```
$ sudo docker run -it mumblevoip/mumble-server bash -c "lscpu"
./docker-entrypoint.sh: line 104: [: : integer expression expected
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       36 bits physical, 48 bits virtual
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               54
Model name:          Intel(R) Atom(TM) CPU D2701   @ 2.13GHz
Stepping:            1
CPU MHz:             2128.029
BogoMIPS:            4256.05
L1d cache:           48 KiB
L1i cache:           64 KiB
L2 cache:            1 MiB
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cm
                     ov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pb
                     e syscall nx lm constant_tsc arch_perfmon pebs bts nopl non
                     stop_tsc aperfmperf pni dtes64 monitor ds_cpl tm2 ssse3 cx1
                     6 xtpr pdcm movbe lahf_lm arat invpcid_single
```

**Comment by azlux** [comment]
Don't you have any config for specific database ?
What's the full output of : `docker run -it --name mumble-server-test mumblevoip/mumble-server` ?

**Comment by DcR-NL** [comment]
Oh, I'm sorry, earlier you meant a custom config for murmur. I didn't get that. No, as you can see in the run command, I haven't linked any volumes/files.

```
$ sudo docker run -it --name mumble-server-test mumblevoip/mumble-server
./docker-entrypoint.sh: line 104: [: : integer expression expected
Command used to start the mumble-server : /usr/bin/mumble-server -fg -ini /etc/murmur/murmur.ini
/usr/bin/mumble-server: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
$
```

**Comment by azlux** [comment]
I've found something about the kernel version of synology.
Some other project have this issue, maybe related to some system kernel call : https://github.com/linuxserver/docker-qbittorrent/issues/103#issuecomment-778827307
What's the output of `uname -a` ?

**Comment by DcR-NL** [comment]
No way:
```
$ uname -a
Linux DS713P 3.10.105 #25556 SMP Tue Aug 3 11:17:03 CST 2021 x86_64 GNU/Linux synology_cedarview_713+
```
Guess that's it, no mumble server for me. *Sad noises* 

Thanks for taking the time to help me out.

**Comment by azlux** [comment]
Maybe you can try this trick : https://github.com/linuxserver/docker-qbittorrent/issues/103#issuecomment-780665097 ?

**Comment by DcR-NL** [comment]
Seems like I would need to fork this and adjust the dockerFile. I can't attach because the container immediately dies in the current state. Apt also returns permission denied. Sudo isn't available. Not sure why. Will take another look tomorrow.

**Comment by azlux** [comment]
use `docker run -it --user=0 mumblevoip/mumble-server bash` to log with root

**Comment by DcR-NL** [comment]
Haha, nice. Already in bed, so had to SSH from my smartphone to replicate the magic, but not without success; murmur is able to boot up. :) Thanks again!

**Comment by fgma** [comment]
I've also experience a problem loading libQt5Core.so.5 which can be fixed by the workaround in @azlux's link. Any chance to integrate this fix directly into the container?

**Comment by fgma** [comment]
I've created a PR to fix this directly in the container.
