### ISSUE TITLE
MUMBLE_SERVERPASSWORD is not saved correctly

### ISSUE THREAD

**Issue by fuuman** [mumble-voip/mumble-docker#15]
I set the environment variable MUMBLE_SERVERPASSWORD in my `docker-compose.yml`. After that I cannot login with that password. When I go into the running container and do `cat /etc/murmur/murmur.ini` I can see that the actual password is set to: `abcdef#serverpassword=ghi` where `abcdef&ghi` is my actual password set.

When I remove the`&` from the passsword it's working. So is that a character that isn't allowed in the password itself?

**Comment by KagurazakaNyaa** [comment]
I have submitted a PR for this issue to be merged
#12

**Comment by azlux** [comment]
The `&` wasn't escaped into the `sed`command. This commit fix the issue.
We will check to create a fix release for that
