### ISSUE TITLE
Different dockerfiles between this and the main repo

### ISSUE THREAD

**Issue by jamezrin** [mumble-voip/mumble-docker#20]
I just started using mumble, and first I used the Dockerfile available at the main repo (https://github.com/mumble-voip/mumble/blob/master/Dockerfile) but then I discovered this which automatically builds and pushes the image to Docker Hub.

I checked the Dockerfiles and they are slightly different, is there a reason for that? Should one be used over the other?

**Comment by Krzmbrzl** [comment]
The reason is simply that this repo is more recent than the Dockerfile in the main repo. I would recommend using this repo though, as we intend to remove the Dockerfile from the main repo in the future (in favor of this one)

**Comment by jamezrin** [comment]
Perfect, thanks for the clarification!

**Comment by Krzmbrzl** [comment]
You're welcome :)
