### ISSUE TITLE
Possibility to read passwords from files

### ISSUE THREAD

**Issue by kalsan** [mumble-voip/mumble-docker#27]
Hi there! Thanks for providing this awesome handy image :-)

To support Docker secrets [1], it would be great if it was possible to provide the values of `SENSITIVE_CONFIGS` kind variables from files instead as just values, similar to how database configurations work.

For example, instead of...:

`MUMBLE_SERVERPASSWORD=oh_noes_i_m_leaking_this_to_the_docker_compose`

...the idea would be to be able to supply...:

`MUMBLE_SERVERPASSWORD_FILE=/run/secrets/mumble_serverpassword`

Thus removing any secrets from `docker-compose.yml`, from `docker run...` bash history, and improving the support for docker swarm etc.

[1]
https://docs.docker.com/engine/swarm/secrets/

Cheers,
Kalsan

**Comment by Krzmbrzl** [comment]
Should be simple enough to implement, but I currently don't have the time for it. Contributions welcome!

**Comment by kalsan** [comment]
Thanks for your answer! In the meantime I found a workaround using a `.env` file, as described in the documentation under https://docs.docker.com/compose/env-file/

While this is not a solution for swarm etc., it effectively solves the problem for me and I'll thus close the issue.

Have a nice day!

**Comment by Krzmbrzl** [comment]
Nah, let's keep this open anyway as this still represents a viable feature request :)

**Comment by maweil** [comment]
Hi there, I really like the idea of using docker/podman secrets for passing values into the container and have implemented a first draft in PR #29.

Do you think requiring the secrets to be mounted in the `/run/secrets/` directory, following the same pattern as the environment variables is a viable alternative to being able to specify the file path to the secret file? 
This is the default location for secrets inside containers when starting them via `podman run --secret MUMBLE_SUPERUSER_PASSWORD ...`

**Comment by kalsan** [comment]
@maweil I wouldn't see why not - I don't think that there is a use case that actually needs these secrets to be somewhere else.

**Comment by maweil** [comment]
With #29 merged for a while now, can we consider this completed? Or is anything still missing in your opinion @kalsan?

**Comment by kalsan** [comment]
@maweil absolutely :-) Thank you very much and have a nice week!
