### ISSUE TITLE
ICE endpoint errors when used with mumo

### ISSUE THREAD

**Issue by Foereaper** [mumble-voip/mumble-docker#33]
Hi!

So I set up a stack with mumo and murmur, and with the default ice configuration to the loopback interface, mumo was not able to connect to the murmur ice instance.

I changed the ice config variable to the following, and mumo was now able to connect:
`ice="tcp -h * -p 6502"
`

However, when I connect with a client that tries to register a callback with a mumo plugin, I get the following error:
```
Added Ice ServerCallback CB16627A-A7FC-47C4-96CE-29AB2AA38001 -o -e 1.0:tcp -h 127.0.0.1 -p 39125 -t 60000
Ice ServerCallback CB16627A-A7FC-47C4-96CE-29AB2AA38001 -o -e 1.0:tcp -h 127.0.0.1 -p 39125 -t 60000 failed
Removed Ice ServerCallback CB16627A-A7FC-47C4-96CE-29AB2AA38001 -o -e 1.0:tcp -h 127.0.0.1 -p 39125 -t 60000
```

I am unsure why it's even trying to register a server callback to the loopback interface, especially on random ports. I tried specifically setting the local IP as the ice IP as well, and it still tries to use 127.0.0.1.

Any ideas? Do I have to use ice published endpoints, and if so, the entrypoint.sh overwrites the ice settings on restart.

**Comment by azlux** [comment]
Hi,
That is why the mumo is set with the config : `network_mode : "service:mumble-server"` on the docker-compose.
This allow docker to share the same network between mumble and mumo, so 127.0.0.1 will work.

**Comment by Foereaper** [comment]
That worked perfectly, thank you very much!
