### ISSUE TITLE
Update Docker Container

### ISSUE THREAD

**Issue by Bunstonious** [mumble-voip/mumble-docker#41]
Id like to try the most recent release and the container on dockerhub is the previous 1.4 release, would either like the docker container updated or instructions to build it myself if possible.

**Comment by Krzmbrzl** [comment]
The new image should be on Dockerhub as soon as https://github.com/mumble-voip/mumble-docker/actions/runs/9180177266 is finished

**Comment by fgma** [comment]
I get the following error after updating the container:

`Error: invalid working directory:  /home/mumble`

Manually creating the folder fixes the issue.

**Comment by s-leon** [comment]
I got:
```
Renaming old tables...

<F>2024-05-21 20:30:05.629 SQL Error [ALTER TABLE `servers` RENAME TO `servers_old_1716323405`]: attempt to write a readonly database Unable to fetch row
```
i have /data volume mounted

**Comment by Bunstonious** [comment]
Thanks for the update :)

I get this message in my logs, do you know if it was build with a different ID other than 1000 as the user context?

*/entrypoint.sh: line 77: /data/mumble_server_config.ini: Permission denied*

Thanks

**Comment by Krzmbrzl** [comment]
Yes the new IDs are 10000 as for some reason 1000 is already taken in Ubuntu 22.04 👀

**Comment by ghost** [comment]
Hi !

Can anyone share with me their docker compose that works without the error: 
`/entrypoint.sh: line 77: /data/mumble_server_config.ini: Permission denied`

THANKS !

**Comment by Bunstonious** [comment]
I have updated the user to 10000 and I still get the permission error (and the status is "Restarting (1) 35 seconds"), and when I run it without any variables it doesn't run properly and just sits there until I cancel it.

**Comment by Jojonintendo** [comment]
I've personally run the container on a new volume to see what the permissions were by default. In my case with Podman, it's 109999.

I've then restored the volume from a backup, and set these permissions, fixed.

**Comment by sambirk** [comment]
```
services:
  mumble:
    container_name: mumble
    image: mumblevoip/mumble-server:latest
    ports:
        - 64738:64738/tcp
        - 64738:64738/udp
    volumes:
      - data:/data
    restart: unless-stopped
volumes:
  data:
```

`sudo chown -R 10000:10000 /var/lib/docker/volumes/mumble_data/`

> Hi !
> 
> Can anyone share with me their docker compose that works without the error: `/entrypoint.sh: line 77: /data/mumble_server_config.ini: Permission denied`
> 
> THANKS !

**Comment by Bunstonious** [comment]
Changing the permissions worked Sambirk, thanks for that (Why I didn't think of doing that, I have no idea T_T ).

**Comment by davidebeatrici** [comment]
> Yes the new IDs are 10000 as for some reason 1000 is already taken in Ubuntu 22.04 👀

1000 is usually the first user's ID.

**Comment by Krzmbrzl** [comment]
It wasn't in 20.04 though :shrug:

**Comment by davidebeatrici** [comment]
Maybe the user was created with an explicit ID.

**Comment by TBhimdi** [comment]
Had the same issue upgrading from the previous docker image, added `user: 1000:1000` in my compose.yaml, fixed it right up.
