### ISSUE TITLE
Issue with --volume

### ISSUE THREAD

**Issue by omnigenous** [mumble-voip/mumble-docker#48]
I'm new to docker and this is not obvious to me. I used command from README:

```sh
docker run --detach --name mumble-server --publish 64738:64738/tcp --publish 64738:64738/udp --volume ./data/mumble:/data --restart on-failure mumblevoip/mumble-server:latest
```

But after downloading an image it throw error:

```
docker: Error response from daemon: create ./data/mumble: "./data/mumble" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```

Not sure if it is related but I had different issue that I solved with https://stackoverflow.com/a/48957722/12038199

**Comment by azlux** [comment]
You can try with 
```
docker run --detach --name mumble-server --publish 64738:64738/tcp --publish 64738:64738/udp --volume "./data/mumble:/data" --restart on-failure mumblevoip/mumble-server:latest
```
I suppose your bash try to interpret the relative path because this volume is a host/container mount point, not a local named volume like the error say. (https://docs.docker.com/engine/storage/volumes/#choose-the--v-or---mount-flag)

**Comment by omnigenous** [comment]
Copied your codeblock but same error :disappointed: 
I'm using zsh but I tried running on bash, just in case, also same error.

**Comment by azlux** [comment]
This line work well on mine.
what is your current docker version ? `docker --version`
I am currently in version 27.3.1

**Comment by omnigenous** [comment]
Oh wow, it's 20.10.24

**Comment by azlux** [comment]
This is the packaged by debian docker version
Not a bad one, it's just a little bit old because packaging docker is a nightmare for the debian team.

Try to use `docker--help` to get the good command for you. It's should not have a big difference for volumes.

**Comment by omnigenous** [comment]
Solved by running to install latest version:

```sh
curl -fsSL https://get.docker.com | sudo sh
```
