### ISSUE TITLE
The image on docker hub doesn't seem to be configured

### ISSUE THREAD

**Issue by KagurazakaNyaa** [mumble-voip/mumble-docker#5]
This image seems to be built and pushed to Docker Hub only through GitHub Action, but the README of this image is not configured on Docker Hub, so visiting https://hub.docker.com/r/mumblevoip/mumble-server returns 404 , so this image is only visible in search results or fetched via docker pull.

**Comment by Krzmbrzl** [comment]
That URL does not return a 404 for me.
Nonetheless, the README is (afaict) indeed not pushed. Do you happen to know how that would work?

**Comment by KagurazakaNyaa** [comment]
This seems to be normal now, perhaps because Docker Hub didn't properly create a public view of this repo at the time and therefore couldn't access this repo on Docker Hub through non-API means.
