### ISSUE TITLE
Please update the docker container image to the latest version as well

### ISSUE THREAD

**Issue by driftywinds** [mumble-voip/mumble-docker#51]
The last tag in https://hub.docker.com/r/mumblevoip/mumble-server/tags is 7 months old even though Mumble keeps releasing stable builds.

**Comment by Krzmbrzl** [comment]
Well, the new version is from 2 days ago. There have been no additional releases in between. So the current release being 7 months old doesn't really say anything other than for the latest release we have not yet gotten around to creating the associated Docker file (and that the automation that should take care of it is still broken).

However, I have now triggered the build of the latest stable Mumble release, which should shortly be available on Dockerhub.

**Comment by driftywinds** [comment]
> Well, the new version is from 2 days ago. There have been no additional releases in between. So the current release being 7 months old doesn't really say anything other than for the latest release we have not yet gotten around to creating the associated Docker file (and that the automation that should take care of it is still broken).
> 
> However, I have now triggered the build of the latest stable Mumble release, which should shortly be available on Dockerhub.

sorry for the confusion, I was new to the project and unaware. Thank you for putting up with me

**Comment by Krzmbrzl** [comment]
No worries :)
