### ISSUE TITLE
Request: add ARM image to docker hub

### ISSUE THREAD

**Issue by CogentRedTester** [mumble-voip/mumble-docker#6]
I run a mumble server on my Raspberry Pi, and it would be really useful to have the official docker image support the device.

**Comment by azlux** [comment]
Hi,
what's the result of the command : `uname -m` ?

**Comment by CogentRedTester** [comment]
My Pi is currently using ARMv7, sorry I should have mentioned it. The result of that command is `armv7l`

**Comment by CogentRedTester** [comment]
Also you probably know this but the error message that comes up is:
```
Pulling mumble-server (mumblevoip/mumble-server:latest)...
latest: Pulling from mumblevoip/mumble-server
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

**Comment by azlux** [comment]
Fixed with https://github.com/mumble-voip/mumble-docker/commit/be59b0bf8d24bb9b4db9ae24d07081050ae1baf4
Can you check ?

**Comment by CogentRedTester** [comment]
Yes it's working, thanks!
