### ISSUE TITLE
Unable to build when https://mumble.info is down

### ISSUE THREAD

**Issue by tomcraft** [mumble-voip/mumble-docker#8]
Hello, I tried building the image myself and I was unable to complete the build resulting in an infinite wait during the `/mumble/repo/scripts/mumble-build-number.py` command because the http://mumble.info/ website is down and never timing-out.

It would be great to not hard-depend on a service like this, possible solutions I see are:
- be able to provide a build-number via build-args
- quickly timeout to default to 0

Thank you for your work and have a nice day ! :)

**Comment by Krzmbrzl** [comment]
Yeah adding  a timeout seems like a good idea in either case. Adding an additional option to specify the build number as build arg directly also sounds good to me :+1:
